#!/usr/bin/env bash
# Transfers a file from a client to a server

if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	return
fi

file_path="$1"
ip="$2"
username="$3"
destination="~/"

if [ "$#" -eq 4 ]
then
	ssh_key_path=$4
	scp -o StrictHostKeyChecking="off" -i "$ssh_key_path" "$username"@"$ip":"$destination" "$file_path"
else
	scp -o StrictHostKeyChecking="off" "$file_path" "$username"@"$ip":"$destination"
fi
