#!/usr/bin/env bash
# Configures URI permanent redirection

sudo apt-get -y update
sudo apt-get -y install nginx

file="/etc/nginx/sites-available/default"
new_string=$"server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/github.com\/Madu-f0r0;\n\t}"
sed -i "s/server_name _;/$new_string/" $file

sudo service nginx start
