#!/usr/bin/env bash
#Creates a permanent redirection for `/redirect_me`

sudo apt update
sudo apt install -y nginx

# Create a new Nginx configuration file for redirection
echo "server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Additional server configurations go here
}" | sudo tee /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled

sudo service nginx start
