#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop
#+ On the 9th iteration "Hi" is also displaye on a new line

i=0
while ((i < 10))
do
	echo "Best School"
	if ((i == 8))
	then
		echo "Hi"
	fi
	((i++))
done
