#!/usr/bin/env bash
# This script configures an Ubuntu server to:
#+ resolve the hostname localhost to 127.0.0.2
#+ resolve the hostname facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.tmp

sed -i 's/127\.0\.0\.1/127.0.0.2/' ~/hosts.tmp
sed -i "\$a8.8.8.8\tfacebook.com" ~/hosts.tmp

sudo cp ~/hosts.tmp /etc/hosts
